---
title: "plyxp: From Tidy Code to Tidy Transcripts"
---

```{r}
source("R/zzz-load.R")

.render_clone <- NULL

render_ <- function(obj, file) {
  .render_clone <<- obj_clone(obj)
  render_gif(obj, file, width = 1400, height = 700, loop = 1,
    fps = 25, clone = FALSE, 
    units = "px")
}


```

```{r}


w_w <- 10
w_h <- 5
w <- window(bl = 0, tr = pos(w_w, w_h))
trk <- tracker(w)
.c <- center(w)
.size <- w_h * 0.9

.assay <- rect(width = .size, height = .size, color = "#8BD79188",
  trans = transform(.c))


w@child(
  .assay@action(
    spawn_grid(
      nrow = 10, ncol = 8, color = "#8BB85F",
      padding = 0.15,
      xtime = 0.1,
      apply = \(x) {obj_scale(x, size = -1)},
      action = list(scale2(size = 1.2, time = time(.7))@
       then(scale2(size = -.2, time = time(.2))))
    )
  )
)

trk@track(.assay = .assay)

render_(w, "assay_example.gif")
bk0 <- trk@clone()
```

```{r}
trk <- bk0@restore()
w <- trk@object
pal <- scales::pal_gradient_n(scales::pal_viridis(1, 0, 1, 1, "D")(6))

set.seed(123)
lapply(.assay@children, \(child) {
  # each shape is an environment
  # it supports arbitrary storage
  child$start <- child@color
  child$val <- runif(1)
  child$end <- pal(child$val)
  child@action(
    color(child$start, child$end, time = time(3, ease = ease(ecubic)))
  )
}) |> invisible()


render_(w, "assay_color.gif")
bk1 <- trk@clone()
```

```{r}


scale_top <- function(size, time) {
  time <- new_time(time)
  action(function(obj, time) {
    force(time)
    if (is.null(time$from)) {
      time$from <- obj_size(obj)
      .clone <- obj_scale(obj_clone(obj), size = size)
      time$width <- .clone@width
      time$height <- .clone@height
      time$around <- tc(.clone)
    }
    from <- time$from
    height <-  time$height * time@value
    obj@height <- height
    obj@width <- time$width
    obj_translate(obj, pos(time$around$x, time$around$y - (height / 2)))
  }, time = time)
}
```

```{r}
trk <- bk1@restore()
w <- trk@object

.lc <- lc(.assay)
.rows <- rect(height = .assay@height, width = .lc$x * 0.8,
  transform(
    pos(mean(c(0, .lc$x)), .lc$y) 
  ),
  color = "#AC94CA00"
) 
w@child(.rows)
trk@track(.rows = .rows)

.rows@action(
  color(
    "#AC94CA00", "#AC94CAFF", time = time(1, ease = ecubic)
  )@then(
    spawn_grid(nrow = 1, ncol = 3, xtime = 0, 
      color = "#AC43CE", ypadding = .02, xpadding = .1,
      apply = \(x) obj_scale(x, size = -1),
    actions = list(
      scale_top(size = 1, 
        time = time(.4, ease = ease(ecubic, ecubic))
      )@then(
        spawn_grid(nrow = 10, ncol = 1, xtime = 0,
          color = "#AC6ACA", padding = .2,
          apply = \(x) obj_scale(x, size = -1),
          action = list(scale2(size = 1, time = time(.7)))
        )
      )))
  )
)

render_(w, "assay_rows.gif" )
bk2 <- obj_clone(trk)
```

```{r}
trk <- bk2@restore()
w <- trk@object
rpal <- scales::pal_gradient_n(scales::pal_viridis(1, 0, 1, 1, "C")(6))

set.seed(42)

.rows@children[[1]]@children |> lapply(
  function(child) {
    child$start <- child@color
    child$val <- sample(c(0,.333,.6666,1), 1)
    child$end <- rpal(child$val)
    child@action(
      color(child$start, child$end, time = time(2, ease = ease(ecubic)))
    )
  }
) |> invisible()

.rows@children[[2]]@children |> lapply(
  function(child) {
    child$start <- child@color
    child$val <- sample(c(.2,.5, .7, .8), 1)
    child$end <- rpal(child$val)
    child@action(
      color(child$start, child$end, time = time(2, ease = ease(ecubic)))
    )
  }
) |> invisible()

.rows@children[[3]]@children |> lapply(
  function(child) {
    child$start <- child@color
    child$val <- runif(1)
    child$end <- rpal(child$val)
    child@action(
      color(child$start, child$end, time = time(2, ease = ease(ecubic)))
    )
  }
) |> invisible()

render_(w, "rows_color.gif")
bk2_2 <- trk@clone()

```

```{r}
local({
  .g1 <- magick::image_read("assay_rows.gif")
  .g2 <- magick::image_read("rows_color.gif")
  magick::image_animate(c(.g1, .g2), fps = 25, loop = 1) |>
  magick::image_write("assay_rows_color.gif")
})
```

```{r}
trk <- bk2_2@restore()
w <- trk@object
.bl <- bl(.rows)

w@action(
  action(
    function(obj, time) {
      obj_scale(obj@children[[1]], .bl, size = -0.25 * time@delta)      
      obj_scale(obj@children[[2]], .bl, size = -0.25 * time@delta)
    },
    time = time(1.5, ease = ease(ecubic, ecubic))
  )
)
render_(w, "shrink_assay_row.gif")
bk3 <- trk@clone()
```


```{r}
trk <- bk3@restore()
w <- trk@object
"#FFDC8F" #inner
"#FFA909" #column
"#E1C757" #context
.tc <- tc(.assay)
.cols <- rect(height = (5 - .tc$y) * .8 , width = .assay@width,
  transform(
    pos(.tc$x, mean(c(5, .tc$y))) 
  ),
  color = "#E1C75700"
) 
w@child(.cols)
trk@track(.cols = .cols)

.cols@action(
  color(
    "#E1C75700", "#E1C757FF", time = time(1, ease = ecubic)
  )@then(
    spawn_grid(nrow = 2, ncol = 1, xtime = 0, 
      color = "#FFA909", xpadding = .015, ypadding = .1,
      apply = \(x) obj_scale(x, size = -1),
    actions = list(
      scale_top(size = 1, 
        time = time(.4, ease = ease(ecubic, ecubic))
      )@then(
        spawn_grid(nrow = 1, ncol = 8, ytime = 0,
          color = "#FFDC8F", padding = .2, xpadding = .15,
          apply = \(x) obj_scale(x, size = -1),
          action = list(scale2(size = 1, time = time(.7)))
        )
      )))
  )
)

render_(w, "assay_cols.gif" )
bk4 <- trk@clone()
```

```{r}
trk <- bk4@restore()
w <- trk@object
cpal <- scales::pal_gradient_n(RColorBrewer::brewer.pal(name = "YlOrRd", n = 6))
set.seed(31)

.cols@children[[1]]@children |> lapply(
  function(child) {
    child$start <- child@color
    child$val <- sample(c(.1, .9), 1)
    child$end <- cpal(child$val)
    child@action(
      color(child$start, child$end, time = time(2, ease = ease(ecubic)))
    )
  }
) |> invisible()

.cols@children[[2]]@children |> lapply(
  function(child) {
    child$start <- child@color
    child$val <- runif(1)
    child$end <- cpal(child$val)
    child@action(
      color(child$start, child$end, time = time(2, ease = ease(ecubic)))
    )
  }
) |> invisible()

render_(w, "cols_color.gif")
bk4_2 <- trk@clone()
```

```{r}
local({
  .g1 <- magick::image_read("assay_cols.gif")
  .g2 <- magick::image_read("cols_color.gif")
  magick::image_animate(c(.g1, .g2), fps = 25, loop = 1) |>
  magick::image_write("assay_cols_color.gif")
})
```

```{r}
trk <- bk4_2@restore()
w <- trk@object

# reorder children elements position in world space
.assay@children <- .assay@children[
  lapply(.assay@children, obj_pos) |>
  vctrs::list_unchop() |> 
  (\(x) order(x$x, x$y, decreasing = c(FALSE, TRUE)))()]

# container for "unwinding" the SE
.df <- rect(width = 4, height = 5, 
  trans = transform(pos(7.8, 2.5)),
  color = "grey80")

# precompute the destination grid loations, we have
# only 6 variables in the SE and dims are 10x8 = 80
# output is a list length 6, with pos vectors of length 80.
.dest_cache <- calc_grid(
  .df, nrow = 80, ncol = 6,
  ymargin = 1,
  ypadding = 0.01
)
.height <- attr(.dest_cache, "features")["height"]
.width <- attr(.dest_cache, "features")["width"]

# all scaling in package at the moment affect both x and y
# propotionally. this can be used to set the goal height/width
# on the time object
.simple_scale <- function(obj, time) {
  if (is.null(time$dh)) {
    #.height and .width are set above representing
    # the height and width of each computed cell of 
    # the grid.
    time$dh <- .height - obj@height
    time$dw <- .width - obj@width 
  }
  obj@height <- obj@height + (time$dh * time@delta)
  obj@width <- obj@width + (time$dw * time@delta)
}
w@child(.df)
trk@track(.df = .df)
```

```{r}
.time_sc <- NULL
# complicated function
.assay@action(
  action(
    #act on the assay object first
    function(obj, time) {
      # action is wrapped behind the @cycled property,
      # which turns true when the timer finishes a cycle.
      # Thus this action has the effect of triggering at the
      # end. Since the timer is repeating (see below), this
      # field will be reset with the timer.
      if (time@cycled) {
        # on first instance it should be NULL
        if (is.null(time$index)) {
          time$index <- 0L
        }
        # every time we cycle, we increment the index
        time$index <- time$index + 1L
        # make the next time we fire happen a *little* bit faster
        .time_sc <<- time@time_scale <- time@time_scale * 1.01 # accelerate
        # since we organized the children by their global position space,
        # we can use the time$index as an index into this list.
        orig_child <- obj@children[[time$index]]
        # create a clone of the "matrix value", and have that clone
        # move towards the appropriate destination.
        child <- obj_clone(orig_child)@action(
          translate(.dest_cache[[1]][time$index], time = time(.75, ease = ease(ecubic))),
        )@action(
          #chaining @action(<action>)@action(<action>) has the effect of 
          #doing both actions at the same time, so the scaling and
          #translation happen together.
          .simple_scale,
          time = time(.75, ease = ease(ecubic))
        )
        # instantly change the original cells opaqueness so it looks like
        # it's disappearing, while the clone moves and scales to the new
        # location.
        orig_child@color <- opaque(orig_child@color, 0.5)
        spawn_from(.df, child)
      }
    },
    time = time(.1, repeating = 79)
  )
)

render_(w, "unpacking_assay.gif")
bk5 <- trk@clone()
```

```{r}
trk <- bk5@restore()
w <- trk@object
.rtime_sc <- NULL

# similar idea as before execpt we need
# to do this across a matrix of children
# what differes here is how we index into the heirarchy
# and the .dest_cache
.unpack_row <- function(obj, time) {
  if (time@cycled) {
    if (is.null(time$col)) {
      time$col <- 1L
      time$i <- 0L
    }
    if (is.null(time$index) || time$index == 10L) {
      time$index <- 0L
    }
    if (time$i == 80) {
      time$i <- 0L
      time$col <- time$col + 1L
    }
    time$i <- time$i + 1L
    time$index <- time$index + 1L
    .rtime_sc <<- time@time_scale <- min(time@time_scale * 1.01, 70) # accelerate
    column <- obj@children[[time$col]]
    orig_child <- column@children[[time$index]]
    child <- obj_clone(orig_child)@action(
      translate(.dest_cache[[time$col + 1L]][time$i],
        time = time(.75, ease = ease(ecubic))),
    )@action(
      .simple_scale,
      time = time(.75, ease = ease(ecubic))
    )
    orig_child@color <- opaque(orig_child@color, 
      opaqueness(orig_child@color) - 0.0625)
    spawn_from(.df, child)
  }
}

.rows@action(
  action(
    function(obj, time) {
      if (time@cycled) {
        time@reset()
      }
      if (length(.assay@actions) == 0L) {
        time@cycled <- TRUE
        time@iter <- time@iter + 1L
      }
    },
    # inf time is conditional
    time = time(1)
  )@then(
    action(
      .unpack_row,
      time = time(1 / .time_sc, repeating = 239)
    )
  )
  
)

render_(w, "unpacking_rows.gif")
bk6 <- trk@clone()
```

```{r}
trk <- bk6@restore()
w <- trk@object
# similar idea as before execpt we need
# to do this across a matrix of children
# what differes here is how we index into the heirarchy
# and the .dest_cache
.unpack_col <- function(obj, time) {
  if (time@cycled) {
    if (is.null(time$col)) {
      time$col <- 1L
      time$i <- 0L
    }
    if (is.null(time$index)) {
      time$index <- 0L
    }
    if (time$i == 80) {
      time$i <- 0L
      time$col <- time$col + 1L
      time$index <- 0L
    }
    
    
    time$i <- time$i + 1L
    
    if ((time$i - 1L) %% 10L == 0L) {
      time$index <- time$index + 1L
    }
    
    time@time_scale <- min(time@time_scale * 1.01, 70) # accelerate
    column <- obj@children[[time$col]]
    orig_child <- column@children[[time$index]]
    child <- obj_clone(orig_child)@action(
      translate(.dest_cache[[time$col + 4L]][time$i],
        time = time(.75, ease = ease(ecubic))),
    )@action(
      .simple_scale,
      time = time(.75, ease = ease(ecubic))
    )
    orig_child@color <- opaque(orig_child@color, 
      opaqueness(orig_child@color) - 0.0625)
    spawn_from(.df, child)
  }
}

.cols@action(
  action(
    function(obj, time) {
      if (time@cycled) {
        time@reset()
      }
      if (length(.rows@actions) == 0L) {
        time@cycled <- TRUE
        time@iter <- time@iter + 1L
      }
    },
    # inf time is conditional
    time = time(1)
  )@then(
    action(
      .unpack_col,
      time = time(1/40, repeating = 159)
    )
  )
  
)

render_(w, "unpacking_cols.gif")
bk7 <- trk@clone()
```

```{r}
local({
  .g1 <- magick::image_read("unpacking_assay.gif")
  .g2 <- magick::image_read("unpacking_rows.gif")
  .g3 <- magick::image_read("unpacking_cols.gif")
  magick::image_animate(c(.g1, .g2, .g3), fps = 25, loop = 1) |>
  magick::image_write("unpacking.gif")
})

```
